src/ITLearning.Frontend.Web/Controllers/LandingController.cs
using ITLearning.Frontend.Web.Controllers.Base;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;

namespace ITLearning.Frontend.Web.Controllers
{
    [AllowAnonymous]
    [Route("")]
    public class LandingController : BaseController
    {
        [HttpGet("")]
        public IActionResult Index()
        {
            if (IsAuthorized())
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
    }
}

src/ITLearning.Frontend.Web/Views/Shared/Partials/Footer.cshtml
<footer>
    <a asp-action="Index" asp-controller="Home">IT Learning <span class="beta-sign">(beta)</span> | @DateTime.Today.Year</a>
</footer>

src/ITLearning.Frontend.Web/Views/Shared/Partials/Header.cshtml
<header class="sliding-header">
    <div class="overlay"></div>
    <div class="header-wrapper">
        <h2 class="header-brand">
            <a asp-action="Index" asp-controller="Landing">IT Learning <span class="beta-sign">(beta)</span></a>
        </h2>
    </div>
    <div class="menu-wrapper">
        <h2 class="menu-title menu-title-toggle">
            <span><i class="fa fa-bars menu-icon"></i></span> <span class="wide-screen-text">Menu</span>
        </h2>
        <nav class="menu">
            @Html.Partial("~/Views/Shared/Partials/SideMenu.cshtml")
        </nav>
    </div>
</header>

src/ITLearning.Frontend.Web/Views/Shared/Partials/SideMenu.cshtml
@if (User.Identity.IsAuthenticated)
{
    <ul class="menu-list">
        <li class="menu-group">
            <p class="menu-group-title">@($"Witaj, {User.Identity.Name}!")</p>
            <ul class="menu-group-items">
                <li><a asp-action="Profile" asp-controller="User"><i class="fa fa-user"></i> Twój profil</a></li>
            </ul>
        </li>
        <li class="menu-group">
            <p class="menu-group-title">Nauka</p>
            <ul class="menu-group-items">
                <li><a href="/Tasks/TasksList/"><i class="fa fa-code"></i> Zadania</a></li>
                <li><a asp-action="Index" asp-controller="Groups"><i class="fa fa-users"></i> Grupy</a></li>
            </ul>
        </li>
        <li class="menu-group">
            <p class="menu-group-title">Więcej</p>
            <ul class="menu-group-items">
                <li><a asp-action="All" asp-controller="News"><i class="fa fa-newspaper-o"></i> Newsy</a></li>
                <li><a asp-action="Logout" asp-controller="Account"><i class="fa fa-arrow-right"></i> Wyloguj się</a></li>
            </ul>
        </li>
    </ul>
}
else
{
    <ul class="menu-list">
        <li class="menu-group">
            <p class="menu-group-title">Witaj w IT Learning</p>
            <ul class="menu-group-items">
                <li><a asp-action="SignUp" asp-controller="Account"><i class="fa fa-user"></i> Załóż konto</a></li>
                <li><a asp-action="Login" asp-controller="Account"><i class="fa fa-arrow-right"></i> Zaloguj się</a></li>
            </ul>
        </li>
    </ul>
}